#!/usr/bin/env bash
# Transfer a file from client to server using scp

# Check if all required parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

# Use scp to transfer the file to the user's home directory on the server
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/
