#!/usr/bin/env bash
#using while loop 4-if_9_say_hi

i=0
while [ $i -lt 10 ]
do
    if [ $i == 3 ]
    then
        echo "bad luck"
    elif [ $i == 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
        fi
    i=$((i+1))
done

