#!/usr/bin/env bash
# Fix Apache in Docker container to return a page with "Hello Holberton"

# Run the Docker container
docker run -p 8080:80 -d -it holbertonschool/265-0

# Check running containers
docker ps

# Connect to container Bash
docker exec -ti CONTAINER_ID /bin/bash

# Investigate and fix Apache configuration if needed
# Restart Apache service

service apache2 restart

# Exit container Bash
exit
