#!/usr/bin/env bash
# Transfer a file from client to server using scp

# Check if all required parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4
echo "variable0=$0 FILE_PATH=$FILE_PATH SERVER_IP=$SERVER_IP USERNAME=$USERNAME SSH_KEY=$SSH_KEY  "


